// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Bpftrace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 可选错误消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_Bpftrace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Bpftrace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_Bpftrace_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BpftraceFlags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathScript    string                 `protobuf:"bytes,1,opt,name=path_script,json=pathScript,proto3" json:"path_script,omitempty"`
	PathBin       string                 `protobuf:"bytes,2,opt,name=path_bin,json=pathBin,proto3" json:"path_bin,omitempty"`
	Vars          string                 `protobuf:"bytes,3,opt,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BpftraceFlags) Reset() {
	*x = BpftraceFlags{}
	mi := &file_Bpftrace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BpftraceFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpftraceFlags) ProtoMessage() {}

func (x *BpftraceFlags) ProtoReflect() protoreflect.Message {
	mi := &file_Bpftrace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpftraceFlags.ProtoReflect.Descriptor instead.
func (*BpftraceFlags) Descriptor() ([]byte, []int) {
	return file_Bpftrace_proto_rawDescGZIP(), []int{1}
}

func (x *BpftraceFlags) GetPathScript() string {
	if x != nil {
		return x.PathScript
	}
	return ""
}

func (x *BpftraceFlags) GetPathBin() string {
	if x != nil {
		return x.PathBin
	}
	return ""
}

func (x *BpftraceFlags) GetVars() string {
	if x != nil {
		return x.Vars
	}
	return ""
}

type BpftraceDeleteScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BpftraceDeleteScript) Reset() {
	*x = BpftraceDeleteScript{}
	mi := &file_Bpftrace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BpftraceDeleteScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpftraceDeleteScript) ProtoMessage() {}

func (x *BpftraceDeleteScript) ProtoReflect() protoreflect.Message {
	mi := &file_Bpftrace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpftraceDeleteScript.ProtoReflect.Descriptor instead.
func (*BpftraceDeleteScript) Descriptor() ([]byte, []int) {
	return file_Bpftrace_proto_rawDescGZIP(), []int{2}
}

func (x *BpftraceDeleteScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type BpftraceGetScriptList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	List          []*BpftraceDeleteScript `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BpftraceGetScriptList) Reset() {
	*x = BpftraceGetScriptList{}
	mi := &file_Bpftrace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BpftraceGetScriptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpftraceGetScriptList) ProtoMessage() {}

func (x *BpftraceGetScriptList) ProtoReflect() protoreflect.Message {
	mi := &file_Bpftrace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpftraceGetScriptList.ProtoReflect.Descriptor instead.
func (*BpftraceGetScriptList) Descriptor() ([]byte, []int) {
	return file_Bpftrace_proto_rawDescGZIP(), []int{3}
}

func (x *BpftraceGetScriptList) GetList() []*BpftraceDeleteScript {
	if x != nil {
		return x.List
	}
	return nil
}

var File_Bpftrace_proto protoreflect.FileDescriptor

const file_Bpftrace_proto_rawDesc = "" +
	"\n" +
	"\x0eBpftrace.proto\x12\vbpftrace_pb\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x0eResponseStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\rBpftraceFlags\x12\x1f\n" +
	"\vpath_script\x18\x01 \x01(\tR\n" +
	"pathScript\x12\x19\n" +
	"\bpath_bin\x18\x02 \x01(\tR\apathBin\x12\x12\n" +
	"\x04vars\x18\x03 \x01(\tR\x04vars\".\n" +
	"\x14BpftraceDeleteScript\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"N\n" +
	"\x15BpftraceGetScriptList\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.bpftrace_pb.BpftraceDeleteScriptR\x04list2\xf4\x01\n" +
	"\x0fBpftraceService\x12D\n" +
	"\tRunScript\x12\x1a.bpftrace_pb.BpftraceFlags\x1a\x1b.bpftrace_pb.ResponseStatus\x12N\n" +
	"\fDeleteScript\x12!.bpftrace_pb.BpftraceDeleteScript\x1a\x1b.bpftrace_pb.ResponseStatus\x12K\n" +
	"\rGetScriptList\x12\x16.google.protobuf.Empty\x1a\".bpftrace_pb.BpftraceGetScriptListB\tZ\a/proto/b\x06proto3"

var (
	file_Bpftrace_proto_rawDescOnce sync.Once
	file_Bpftrace_proto_rawDescData []byte
)

func file_Bpftrace_proto_rawDescGZIP() []byte {
	file_Bpftrace_proto_rawDescOnce.Do(func() {
		file_Bpftrace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Bpftrace_proto_rawDesc), len(file_Bpftrace_proto_rawDesc)))
	})
	return file_Bpftrace_proto_rawDescData
}

var file_Bpftrace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Bpftrace_proto_goTypes = []any{
	(*ResponseStatus)(nil),        // 0: bpftrace_pb.ResponseStatus
	(*BpftraceFlags)(nil),         // 1: bpftrace_pb.BpftraceFlags
	(*BpftraceDeleteScript)(nil),  // 2: bpftrace_pb.BpftraceDeleteScript
	(*BpftraceGetScriptList)(nil), // 3: bpftrace_pb.BpftraceGetScriptList
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_Bpftrace_proto_depIdxs = []int32{
	2, // 0: bpftrace_pb.BpftraceGetScriptList.list:type_name -> bpftrace_pb.BpftraceDeleteScript
	1, // 1: bpftrace_pb.BpftraceService.RunScript:input_type -> bpftrace_pb.BpftraceFlags
	2, // 2: bpftrace_pb.BpftraceService.DeleteScript:input_type -> bpftrace_pb.BpftraceDeleteScript
	4, // 3: bpftrace_pb.BpftraceService.GetScriptList:input_type -> google.protobuf.Empty
	0, // 4: bpftrace_pb.BpftraceService.RunScript:output_type -> bpftrace_pb.ResponseStatus
	0, // 5: bpftrace_pb.BpftraceService.DeleteScript:output_type -> bpftrace_pb.ResponseStatus
	3, // 6: bpftrace_pb.BpftraceService.GetScriptList:output_type -> bpftrace_pb.BpftraceGetScriptList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Bpftrace_proto_init() }
func file_Bpftrace_proto_init() {
	if File_Bpftrace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Bpftrace_proto_rawDesc), len(file_Bpftrace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Bpftrace_proto_goTypes,
		DependencyIndexes: file_Bpftrace_proto_depIdxs,
		MessageInfos:      file_Bpftrace_proto_msgTypes,
	}.Build()
	File_Bpftrace_proto = out.File
	file_Bpftrace_proto_goTypes = nil
	file_Bpftrace_proto_depIdxs = nil
}
